apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce       # un solo nodo monta el volumen (suficiente para una BD primaria)
  storageClassName: gp2   # clase de almacenamiento estándar en EKS (EBS gp2)
  resources:
    requests:
      storage: 5Gi
