apiVersion: v1
kind: Service
metadata:
  name: casino-postgres    # este nombre es el DB_HOST que usan todos los servicios
  labels:
    app: casino-postgres
spec:
  type: ClusterIP
  selector:
    app: casino-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
